//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hethong_tuyendung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoXinViec
    {
        public HoSoXinViec()
        {
            this.NopHoSo = new HashSet<NopHoSo>();
        }
    
        public int Ma_HS { get; set; }
        public string Ten_HS { get; set; }
        public int Ma_NTV { get; set; }
        public System.DateTime NgayNop { get; set; }
        public string KinhNghiem { get; set; }
        public string NgoaiNgu { get; set; }
        public string TrinhDo { get; set; }
        public string ViTriMongMuon { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NguoiTimViec NguoiTimViec { get; set; }
        public virtual ICollection<NopHoSo> NopHoSo { get; set; }
    }
}
