//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hethong_tuyendung.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HT_tuyendungEntities : DbContext
    {
        public HT_tuyendungEntities()
            : base("name=HT_tuyendungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CongViec> CongViec { get; set; }
        public virtual DbSet<HoSoXinViec> HoSoXinViec { get; set; }
        public virtual DbSet<KNVL> KNVL { get; set; }
        public virtual DbSet<KyNang> KyNang { get; set; }
        public virtual DbSet<NopHoSo> NopHoSo { get; set; }
        public virtual DbSet<NTD_CongViec> NTD_CongViec { get; set; }
        public virtual DbSet<NganhNghe> NganhNghe { get; set; }
        public virtual DbSet<NganhNgheTuyenDung> NganhNgheTuyenDung { get; set; }
        public virtual DbSet<NguoiTimViec> NguoiTimViec { get; set; }
        public virtual DbSet<NhaTuyenDung> NhaTuyenDung { get; set; }
    }
}
