//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hethong_tuyendung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KyNang
    {
        public KyNang()
        {
            this.KNVL = new HashSet<KNVL>();
        }
    
        public int Ma_KN { get; set; }
        public string TenKN { get; set; }
        public string MoTa { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<KNVL> KNVL { get; set; }
    }
}
