//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hethong_tuyendung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiTimViec
    {
        public NguoiTimViec()
        {
            this.HoSoXinViec = new HashSet<HoSoXinViec>();
        }
    
        public int Ma_NTV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<HoSoXinViec> HoSoXinViec { get; set; }
    }
}
