//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hethong_tuyendung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTuyenDung
    {
        public NhaTuyenDung()
        {
            this.NopHoSo = new HashSet<NopHoSo>();
            this.NTD_CongViec = new HashSet<NTD_CongViec>();
            this.NganhNgheTuyenDung = new HashSet<NganhNgheTuyenDung>();
        }
    
        public int Ma_NTD { get; set; }
        public string Ten_cty { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string Fax { get; set; }
        public string DiaChi { get; set; }
        public string QuyMo { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<NopHoSo> NopHoSo { get; set; }
        public virtual ICollection<NTD_CongViec> NTD_CongViec { get; set; }
        public virtual ICollection<NganhNgheTuyenDung> NganhNgheTuyenDung { get; set; }
    }
}
