//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hethong_tuyendung.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTD_CongViec
    {
        public int Ma_CV { get; set; }
        public int Ma_NTD { get; set; }
        public string Mo_ta { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual NhaTuyenDung NhaTuyenDung { get; set; }
    }
}
